# api.py
import json
import os
import time
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse, FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional

from orchestration.task_manager import TaskManager

app = FastAPI()

# Allow requests from your frontend, Django API proxy, and local development
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://www.franciscodes.com",       # your React frontend
        "https://api.franciscodes.com",       # Django backend
        "http://localhost:3000",               # local dev
    ],
    allow_methods=["*"],
    allow_headers=["*"],
)

manager = TaskManager()

class MissionRequest(BaseModel):
    mission: str
    agents: Optional[List[dict]] = []   # completely optional – CEO hires its own team

@app.post("/missions/start")
async def start_mission(req: MissionRequest):
    from gm import NativeAgent, get_population

    if req.agents:
        agents = [NativeAgent(**a) for a in req.agents]
    else:
        # No agents provided – load the empire's population (CEO, QA, DNA agents)
        agents = get_population()

    task_id = manager.start_mission(req.mission, agents)
    return {"task_id": task_id}

@app.get("/missions/{task_id}/stream")
async def stream(task_id: str):
    task = manager.get_task(task_id)
    if not task:
        raise HTTPException(status_code=404)

    def event_generator():
        last = 0
        while not task.is_complete:
            while last < len(task.logs):
                yield f"data: {json.dumps(task.logs[last])}\n\n"
                last += 1
            time.sleep(0.5)
        yield f"data: {json.dumps({'status':'COMPLETE','result':task.result})}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")

@app.get("/missions/{task_id}/artifacts/{filename}")
async def get_artifact(task_id: str, filename: str):
    """
    Fetch any artifact generated by a mission.
    """
    # Security: prevent path traversal attacks (e.g., ../../etc/passwd)
    safe_filename = os.path.basename(filename)
    file_path = f"ai_civilization/scratch/mission_{task_id}/{safe_filename}"

    if not os.path.exists(file_path):
        raise HTTPException(
            status_code=404,
            detail=f"Artifact '{safe_filename}' not found or mission incomplete"
        )

    # FileResponse streams the file and sets the correct Content-Type automatically
    return FileResponse(file_path)
